[toolchain]
anchor_version = "0.32.1"
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sentinel_guardian = "2Fi9UPVbD77Cr2SerjKkpPtbejYXdaa6D4R3Pjor4kQs"
mock_protocol     = "HyUb8Ffara4byitYExmbjbA37Ja7By8fECpG6dFyg8Ln"

[programs.devnet]
sentinel_guardian = "2Fi9UPVbD77Cr2SerjKkpPtbejYXdaa6D4R3Pjor4kQs"
mock_protocol     = "HyUb8Ffara4byitYExmbjbA37Ja7By8fECpG6dFyg8Ln"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "bun run test"